language: node_js
node_js:
  - "10.19.0"
before_install:
  - "npm i -g npm@6.13.4"
branches:
  only:
    - master
    - next
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
jobs:
  include:
    - stage: lint & unit-test
      script:
        - "npm run lint"
        - "npm run unit-test"
