language: node_js
node_js:
  - "9.5.0"
before_install:
  - "npm i -g npm@6.0.1"
branches:
  only:
    - master
    - next
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
jobs:
  include:
    - script:
        # - "npm run lint"  # this, once smart contracts have been cleaned (solhint accepts them)
        - "npm run lint-temporary"
      stage: "linters"
    - script:
        # - "npm run test"  # this, once truffle tests work
        - "npm run test-temporary"
      stage: "smart contract tests"
