name: Continuos Integration

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
        node_version:
          - 10.19.x
          - 12.x
        architecture:
          - x64
    env:
      DEBUG: '*'
      TEST_TIMEOUT: '600000'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Run lint, build and unit test
        run: |
          npm run lint
          npm run build
          npm run unit-test
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.3
        with:
          services-to-start: 'parity-sidechain-node0 parity-node0 bridge'
      - name: Integration Test
        run: npm run integration-test
